- hosts: localhost
  vars:
    version_tag: {{ image_version.stdout }}
    registry: registry.redhat.io
  vars_prompt:
    - name: "user"
      prompt: "Docker Registry Username?"
    - name: "pass"
      prompt: "Docker Registry Password?"
  tasks:
  - name: Log into RH private registry and force re-authorization
    docker_login:
      registry: "{{ registry }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      reauthorize: yes

  - name: pull optional components images for cfme and glusterfs with the latest tag
    docker_image:
      name: "{{ registry}}/{{ item }}"
    with_items:
      - rhgs3/rhgs-server-rhel7
      - rhgs3/rhgs-volmanager-rhel7
      - rhgs3/rhgs-gluster-block-prov-rhel7
      - rhgs3/rhgs-s3-server-rhel7

   - name: Registering version tag
     shell: echo $(docker inspect $registry/$line | grep -m1 version | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//')
     register: image_version

  - name: Tag with vX.Y.Z version label and push to local registry
    docker_image:
      name: "{{ registry }}/{{ item }}"
      repository: localhost:5000/{{ item }}
      tag: "{{ version_tag }}"
      push: yes
    with_items:
      - rhgs3/rhgs-server-rhel7
      - rhgs3/rhgs-volmanager-rhel7
      - rhgs3/rhgs-gluster-block-prov-rhel7
      - rhgs3/rhgs-s3-server-rhel7

  - name: Remove images
    docker_image:
      state: absent
      name: "{{ registry }}/{{ item }}"
      tag: latest
    with_items:
      - rhgs3/rhgs-server-rhel7
      - rhgs3/rhgs-volmanager-rhel7
      - rhgs3/rhgs-gluster-block-prov-rhel7
      - rhgs3/rhgs-s3-server-rhel7

  - name: Remove images
    docker_image:
      state: absent
      name: "{{ registry }}/{{ item }}"
      tag: "{{ version_tag }}"
    with_items:
      - rhgs3/rhgs-server-rhel7
      - rhgs3/rhgs-volmanager-rhel7
      - rhgs3/rhgs-gluster-block-prov-rhel7
      - rhgs3/rhgs-s3-server-rhel7

...
